name: Publish Alpha

on:
  workflow_call:

jobs:
  publish_alpha:
    uses: OpenVoiceOS/gh-automations/.github/workflows/publish_alpha.yml@dev
    with:
      python-version: "3.11"
      version-file: "ovos_ww_plugin_microwakeword/version.py"
    secrets: inherit
